# Generated by Django 3.2.7 on 2021-10-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PangoVarsion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('pangolin_version', models.CharField(blank=True, default=None, max_length=225, null=True)),
                ('pangoLEARN_version', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('pango_version', models.CharField(blank=True, default=None, max_length=225, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='tsvfile',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('strain', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('lineage', models.CharField(blank=True, default=None, max_length=225, null=True)),
                ('gene', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('reference_id', models.CharField(blank=True, default=None, max_length=225, null=True)),
                ('amino_acid_position', models.CharField(blank=True, default=None, max_length=225, null=True)),
                ('mutation', models.CharField(blank=True, default=None, max_length=225, null=True)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('mutation_deletion', models.CharField(blank=True, default=None, max_length=300, null=True)),
            ],
        ),
    ]
