# Generated by Django 3.2.7 on 2021-09-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tsvfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strain', models.CharField(max_length=300)),
                ('lineage', models.CharField(max_length=225)),
                ('gene', models.CharField(max_length=300)),
                ('reference_id', models.CharField(max_length=225)),
                ('amine_acid_position', models.CharField(max_length=225)),
                ('mutation', models.CharField(max_length=225)),
            ],
        ),
    ]
