# Generated by Django 3.2.7 on 2022-01-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsvfile',
            name='month_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tsvfile',
            name='week_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
