# Generated by Django 3.2.7 on 2022-05-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextstrain',
            name='region_type',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
