# Generated by Django 3.2.7 on 2022-01-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0002_auto_20220106_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsvfile',
            name='Class',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
