# Generated by Django 3.2.7 on 2021-10-04 06:14

from django.db import migrations, models
import django.utils.timezone
import split.models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0003_auto_20210926_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsvfile',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=split.models.random_date),
            preserve_default=False,
        ),
    ]
