# Generated by Django 3.2.7 on 2021-10-04 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0005_alter_tsvfile_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tsvfile',
            name='date',
        ),
    ]
