# Generated by Django 3.2.7 on 2021-10-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0006_remove_tsvfile_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsvfile',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
