# Generated by Django 3.2.7 on 2021-10-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0007_tsvfile_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsvfile',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
