# Generated by Django 3.2.7 on 2021-10-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0008_alter_tsvfile_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsvfile',
            name='date',
            field=models.DateField(blank=True, default=None, max_length=225, null=True),
        ),
    ]
