# Generated by Django 3.2.7 on 2021-10-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0012_alter_tsvfile_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tsvfile',
            name='date',
        ),
    ]
